spring:
  application:
    name: gateway-service
  profiles:
    active: #spring.profiles.active#

server:
  servlet:
    context-path: /
---
server:
  port: 7783
spring:
  profiles: dev

---
server:
  port: 7783
spring:
  profiles: test

---
server:
  port: 7783
spring:
  profiles: pro