spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  servlet:
    #上传文件大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10240MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  routes:
    auth:
      path: /auth_service/**
      serviceId: auth
      sensitiveHeaders: "*"
    system:
      path: /system_service/**
      serviceId: system
      sensitiveHeaders: "*"
  retryable: true
  add‐host‐header: true

#eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7782/eureka_service/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: localhost

logging:
  level:
    root: info
    org:
      springframework: info