spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ghw
    url: jdbc:mysql://127.0.0.1:3306/user_db?serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf-8

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    password:
    port: 6379

  servlet:
    #上传文件大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10240MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7782/eureka_service/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    hostname: localhost

security:
  oauth2:
    resource:
      #用于获取当前token的用户信息，配置
      user-info-uri: http://localhost:7781/auth_service/users/current
    #相关信息以及clientId、client-secret等信息要和auth中的配置一一对应。
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:7781/auth_service/oauth/token
      grant-type: client_credentials,password
      scope: server