spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://118.190.143.44:3306/credit_application?serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf-8

  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379

  servlet:
    #上传文件大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10240MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
