spring:
  application:
    name: system-service
  profiles:
    active: #spring.profiles.active#

mybatis:
  type-aliases-package: com.ghw.common.model.system
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

server:
  servlet:
    context-path: /system_service
---
server:
  port: 7780
spring:
  profiles: dev

---
server:
  port: 7780
spring:
  profiles: test

---
server:
  port: 7780
spring:
  profiles: pro