spring:
  application:
    name: system-service
  profiles:
    active: #spring.profiles.active#

server:
  servlet:
    context-path: /system_service
---
server:
  port: 7780
spring:
  profiles: dev

---
server:
  port: 7780
spring:
  profiles: test

---
server:
  port: 7780
spring:
  profiles: pro