spring:
  application:
    name: eureka-service
  profiles:
    active: #spring.profiles.active#

server:
  servlet:
    context-path: /eureka_service
---
server:
  port: 7782
spring:
  profiles: dev

---
server:
  port: 7782
spring:
  profiles: test

---
server:
  port: 7782
spring:
  profiles: pro