spring:
  application:
    name: auth-service
  profiles:
    active: #spring.profiles.active#

server:
  servlet:
    context-path: /auth_service
---
server:
  port: 7781
spring:
  profiles: dev

---
server:
  port: 7781
spring:
  profiles: test

---
server:
  port: 7781
spring:
  profiles: pro